name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.23', '1.22', '1.21', '1.20']
    name: Test on ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Download dependencies
        run: go get -t ./...
      - name: Run tests
        run: go test -v ./...
